version: '2'

services:
  web:
    build: .
    container_name: dictionary
    depends_on: 
      - mongo
    ports:
      - "9000:9000"
    volumes:
      - .:/app  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  