version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dictionary
    depends_on: 
      - mongo
    ports:
      - "9000:9000"
    volumes:
      - .:/app  
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  